# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_auto_20171213_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'SAFE'), ('yellow', 'MINIMAL INJURY'), ('red', 'SEVERE INJURY'), ('black', 'DECEASED')], max_length=30),
        ),
    ]
