# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
