# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admitted',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
