# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_auto_20171214_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/media/profile/user.svg', null=True, upload_to='profile/'),
        ),
    ]
